### PR TITLE
Fix incorrectly-named property

### LINKED ISSUE #41: The interface type/method can't be set
## :ghost: Brief Description

The template for the interfaces contains `@method` variable but it is not set anywhere. We set `@type` which is unused.

I believe the problem was introduced with the change at https://github.com/sous-chefs/network_interfaces/pull/30/commits/22520e9f017fdf7f2982a213668ff265f85f3518 : the template should have kept using `@type` as it already was.

## :pancakes: Cookbook version

Current latest git: 2baefb3c9c7b152c1216c59205193fe1f658a088

## :woman_cook:  Chef-Infra Version

16.12.3

## :tophat: Platform details

Ubuntu 18.04

## Steps To Reproduce
```
include_recipe "network_interfaces"

network_interfaces "lo" do
  type 'loopback'
end
```

## :police_car: Expected behavior

We should get `iface lo inet loopback`. Instead, the `type` is ignored.

### PR DESCRIPTION
**Pull request by jeffbyrnes**
h/t to @Fuuzetsu

Introduced in 22520e9
Merged via #30
Fixes #41

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by axelrtgs — DISMISSED** [review]
Change looks ok to me.

You might need to add the workflow for the tests to run so the check pass though.

**Review by majormoses — DISMISSED** [review]
LGTM

**Comment by Xorima** [comment]
not sure if I am seeing this wrong but I only see a changelog entry and not the change to the template?

**Comment by Fuuzetsu** [comment]
> not sure if I am seeing this wrong but I only see a changelog entry and not the change to the template?

Presumably it's due to this:

> @jeffbyrnes jeffbyrnes force-pushed the fix-mismatched-property-name branch from fe88c7d to 701942a 19 hours ago 

fe88c7d contained the actual change, 701942a does not...

**Comment by jeffbyrnes** [comment]
Bwahahaha, oh man, I accidentally included this in #44 via fe88c7d7d28000cc8c8a938dfd72e99565ac3ebf, so this is already all set!

**Pull request closed without merging**
