### PR TITLE
Feature/multiaddress

### PR DESCRIPTION
**Pull request by akashihi**
Added support for ipv6 and several addresses on a single interface (wheezy+)

### CODE REVIEW

**Comment by guilhem** [comment]
@akashihi I will not support multiple target, this can be easily done with a loop.

Concerning family, can you test this branch: https://github.com/redguide/network_interfaces/tree/LWRP_improvements ?

**Comment by akashihi** [comment]
@guilhem As fo family and 'LWRP_improvements" - it works just great ;) 

Regarding multiple targets, could you please provide an example of such loop? I tried with the most obvious config (on LWRP_improvements) and it failed. So, as LWRP_improvements branch introduces 'family' attribute, it is still useless, as we can't put v4 and v6 address on the interface at the same time.

network_interfaces 'eth1' do
  target "fc00:dead:beef:feca::1"
  family "inet6"
  mask "64"
end

network_interfaces 'eth1' do
  target "192.168.1.1"
  mask "255.255.255.0"
end

==> default: ================================================================================
==> default: Error executing action `create` on resource 'template[/etc/network/interfaces.d/eth1]'
==> default: ================================================================================
==> default:
==> default: Chef::Exceptions::ChecksumMismatch
==> default: ----------------------------------
==> default: Checksum on resource (90043b) does not match checksum on content (1ffb50)
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef/8d117458411bcb9ceb8e35395bf1edb6/cookbooks/network_interfaces/providers/default.rb
==> default:
==> default:  46:   template "/etc/network/interfaces.d/#{new_resource.device}" do
==> default:  47:     cookbook 'network_interfaces'
==> default:  48:     source 'interfaces.erb'
==> default:  49:     owner 'root'
==> default:  50:     group 'root'
==> default:  51:     mode '0644'
==> default:  52:     variables(
==> default:  53:       auto:         Chef::Recipe::NetworkInterfaces.value(:onboot,     new_resource.device, new_resource, node),
==> default:  54:       method: Chef::Recipe::NetworkInterfaces.value(:method,     new_resource.device, new_resource, node) || method,
==> default:  55:       device:       new_resource.device,
==> default:  56:       family:       Chef::Recipe::NetworkInterfaces.value(:family,     new_resource.device, new_resource, node),
==> default:  57:       address:      Chef::Recipe::NetworkInterfaces.value(:target,     new_resource.device, new_resource, node),
==> default:  58:       network:      Chef::Recipe::NetworkInterfaces.value(:network,    new_resource.device, new_resource, node),
==> default:  59:       netmask:      Chef::Recipe::NetworkInterfaces.value(:mask,       new_resource.device, new_resource, node),
==> default:  60:       gateway:      Chef::Recipe::NetworkInterfaces.value(:gateway,    new_resource.device, new_resource, node),
==> default:  61:       broadcast:    Chef::Recipe::NetworkInterfaces.value(:broadcast,  new_resource.device, new_resource, node),
==> default:  62:       bridge_ports: Chef::Recipe::NetworkInterfaces.value(:bridge,     new_resource.device, new_resource, node),
==> default:  63:       bridge_stp:   Chef::Recipe::NetworkInterfaces.value(:bridge_stp, new_resource.device, new_resource, node),
==> default:  64:       vlan_dev:     Chef::Recipe::NetworkInterfaces.value(:vlan_dev,   new_resource.device, new_resource, node),
==> default:  65:       bond_slaves:  Chef::Recipe::NetworkInterfaces.value(:bond,       new_resource.device, new_resource, node),
==> default:  66:       bond_mode:    Chef::Recipe::NetworkInterfaces.value(:bond_mode,  new_resource.device, new_resource, node),
==> default:  67:       metric:       Chef::Recipe::NetworkInterfaces.value(:metric,     new_resource.device, new_resource, node),
==> default:  68:       mtu:          Chef::Recipe::NetworkInterfaces.value(:mtu,        new_resource.device, new_resource, node),
==> default:  69:       up_down_cmd: up_down_cmd,
==> default:  70:       custom:       Chef::Recipe::NetworkInterfaces.value(:custom,     new_resource.device, new_resource, node)
==> default:  71:     )
==> default:  72:     notifies :run, "execute[if_up #{new_resource.name}]", :immediately
==> default:  73:   end
==> default:  74:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef/8d117458411bcb9ceb8e35395bf1edb6/cookbooks/network_interfaces/providers/default.rb:46:in `block in class_from_file'
==> default:
==> default: template("/etc/network/interfaces.d/eth1") do
==> default:   action "create"
==> default:   updated true
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   path "/etc/network/interfaces.d/eth1"
==> default:   backup 5
==> default:   atomic_update true
==> default:   diff "--- /etc/network/interfaces.d/eth1\t2015-05-19 18:19:54.609557764 +0000\\n+++ /tmp/chef-rendered-template20150519-4681-19gh0s2\t2015-05-19 18:20:45.374289883 +0000\\n@@ -1,6 +1,6 @@\\n auto eth1\\n-iface eth1 inet static\\n-  address 192.168.1.1\\n-  netmask 255.255.255.0\\n+iface eth1 inet6 static\\n+  address fc00:dead:beef:feca::1\\n+  netmask 64\\n "
==> default:   source "interfaces.erb"
==> default:   cookbook "network_interfaces"
==> default:   variables {:auto=>true, :method=>"static", :device=>"eth1", :family=>"inet6", :address=>"192.168.1.1", :network=>nil, :netmask=>"255.255.255.0", :gateway=>nil, :broadcast=>nil, :bridge_ports=>nil, :bridge_stp=>nil, :vlan_dev=>nil, :bond_slaves=>nil, :bond_mode=>nil, :metric=>nil, :mtu=>nil, :up_down_cmd=>{:pre_up=>[], :up=>[], :post_up=>[], :pre_down=>[], :down=>[], :post_down=>[]}, :custom=>nil}
==> default:   declared_type :template
==> default:   cookbook_name :network_interfaces
==> default:   owner "root"
==> default:   group "root"
==> default:   mode "0644"
==> default:   checksum "90043bf77b5c5919e2235b1e90b977402face6806dcd8a9ec72d402424ac0b8c"
==> default: end

**Comment by guilhem** [comment]
@akashihi you can use something like that:

```ruby
network_interfaces 'eth1_ipv6' do
  device 'eth1'
  target "fc00:dead:beef:feca::1"
  family "inet6"
  mask "64"
end

network_interfaces 'eth1_ipv4' do
  device 'eth1'
  target "192.168.1.1"
  mask "255.255.255.0"
end
```

**Comment by guilhem** [comment]
@akashihi fixed in 8d5aed6

**Comment by akashihi** [comment]
Well, it is really fixed from at chef side - files are created correctly and everything looks good. But debian doesn't accepts that configuration. So, my test recipe is:

network_interfaces 'eth1' do
  device "eth1"
  target "fc00:dead:beef:cafe::1"
  family "inet6"
  mask "64"
  gateway "fc00:dead:beef:cafe::AA"
end

network_interfaces 'eth1_1' do
  device "eth1"
  target "fc00:dead:beef:feca::1"
  family "inet6"
  mask "64"
end

network_interfaces 'eth1_v4' do
  device "eth1"
  target "192.168.1.1"
  mask "255.255.255.0"
end

It generates following config:
root@fs-storage-berkshelf:/etc/network/interfaces.d# ls
eth1  eth1_1  eth1_v4
root@fs-storage-berkshelf:/etc/network/interfaces.d# cat *
auto eth1
iface eth1 inet6 static
  address fc00:dead:beef:cafe::1
  netmask 64
  gateway fc00:dead:beef:cafe::AA

auto eth1
iface eth1 inet6 static
  address fc00:dead:beef:feca::1
  netmask 64

auto eth1
iface eth1 inet static
  address 192.168.1.1
  netmask 255.255.255.0


And when i try to apply it, it fails:
root@fs-storage-berkshelf:/home/vagrant# ip addr list dev eth1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:22:13:08 brd ff:ff:ff:ff:ff:ff
    inet6 fc00:dead:beef:cafe::1/64 scope global
       valid_lft forever preferred_lft forever


root@fs-storage-berkshelf:/home/vagrant# ifup eth1
/etc/network/interfaces.d/eth1_1:1: interface eth1 declared allow-auto twice
/etc/network/interfaces.d/eth1_v4:1: interface eth1 declared allow-auto twice


TBH, i've tried that approach with my first attempt to implement several addresses on the interface and i failed at exactly same place :)

**Comment by guilhem** [comment]
okay :disappointed:

**Comment by guilhem** [comment]
for a quick and dirty fix, you can put `onboot` to `false` on all except 1.

**Comment by akashihi** [comment]
NP, as i'm using my patch at the moment ;)

Anyway, that should be fixed at the published cookbook. I like your solution (loop over network_interface resource) more then mine :) To make it working you may be need to keep a kind of 'device state' during chef run? It'll help to detect whether you already set the device to auto, did user specified gateway several times etc.

**Comment by guilhem** [comment]
@akashihi yeah I have to do an "accumulator"... But I really hate it :/

**Comment by guilhem** [comment]
@akashihi change my mind, should be fixed in e3916f2a312983a642efd688aa7346f696a48492 :laughing:

**Comment by akashihi** [comment]
@guilhem Works just great right now! Thank you :)

**Comment by Xorima** [comment]
Closing due to inactivity. 

If this is still wanted please reopen or open another pull request. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

**Pull request closed without merging**
