### PR TITLE
Refactor resource

### LINKED ISSUE #41: The interface type/method can't be set
## :ghost: Brief Description

The template for the interfaces contains `@method` variable but it is not set anywhere. We set `@type` which is unused.

I believe the problem was introduced with the change at https://github.com/sous-chefs/network_interfaces/pull/30/commits/22520e9f017fdf7f2982a213668ff265f85f3518 : the template should have kept using `@type` as it already was.

## :pancakes: Cookbook version

Current latest git: 2baefb3c9c7b152c1216c59205193fe1f658a088

## :woman_cook:  Chef-Infra Version

16.12.3

## :tophat: Platform details

Ubuntu 18.04

## Steps To Reproduce
```
include_recipe "network_interfaces"

network_interfaces "lo" do
  type 'loopback'
end
```

## :police_car: Expected behavior

We should get `iface lo inet loopback`. Instead, the `type` is ignored.

### PR DESCRIPTION
**Pull request by jeffbyrnes**
## Description

* Updates test harnesses to use GitHub Actions, so we can satisfy the Sous Chefs’s checks
* Refactors into a Chef 12-style Custom Resource
* Various other nits

## Issues Resolved

Fixes #41 

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by axelrtgs — COMMENTED** [review]
Looks ok to me,

Just some markdown left to fix and to confirm the tests pass now that they are fixed :)

ping me when you need approval after the tests are passing

**Comment by jeffbyrnes** [comment]
@axelrtgs looks good now, though a status is hung, I think? This will unblock #43 as well (I’ll rebase that after this merges, and give you a ping when it’s ready again).

**Review by axelrtgs — APPROVED** [review]

**Comment by jeffbyrnes** [comment]
Hmm; how do we bypass or satisfy the “integration” check?

@tas50 @ramereth perhaps y’all can shed some light?

**Comment by Xorima** [comment]
> 
> 
> Hmm; how do we bypass or satisfy the “integration” check?
> 
> @tas50 @ramereth perhaps y’all can shed some light?

Looks like something I thought would work isn't working :( basically it was meant to group all the ci/integration (OS, Suite) checks into 1 required check, I'll get this fixed today.

**Comment by kitchen-porter** [comment]
Released as: [2.0.0](https://github.com/sous-chefs/network_interfaces/releases/tag/2.0.0)

**Pull request merged**
